name: bump-request

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to change to.
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - uses: r7kamura/bump-request@v0
        with:
          command: |
            sed -i -r 's/([0-9]+\.[0-9]+\.[0-9]+)/${{ inputs.version }}/' lib/*/version.rb
            bundle install
          version: ${{ inputs.version }}
